### ISSUE TITLE
SearchBar 样式问题

### ISSUE THREAD

**Issue by stonexer** [weui/weui-wxss#10]
* 开发工具中取消按钮的 `hidden` 更新为 false 无效，无法显示。（应该是开发工具的 bug）
* SearchBar input 超长时，整个 SearchBar 溢出屏幕，加上 `max-width: 100%` 测试 ok。

**Comment by BearJ** [comment]
@stonexer input为啥会超长的？是人为设置了它的宽度？

**Comment by stonexer** [comment]
@BearJ 因为输入了超长的内容

**Comment by stonexer** [comment]
@BearJ 重新复现了下，发现是我改造之后的问题。case 如下：

没有使用 weui-search-bar__label，一直显示 weui-search-bar__box；
bindBlur 的时候没有清空 input，同时 hidden 掉 weui-search-bar__cancel-btn；
此时如果 input 超长，会溢出屏幕。

我想这不应该是 weui 的问题了。如果有相似需求的，可以考虑给 weui-search-bar__form 加上 `max-width: 100%` 的限制。

**Comment by BearJ** [comment]
赞，谢谢~
