### ISSUE TITLE
请问样式中未能统一用 rpx 的原因是什么？

### ISSUE THREAD

**Issue by BelinChung** [weui/weui-wxss#11]
微信小程序的文档建议尺寸单位是：rpx（responsive pixel），可以根据屏幕宽度进行自适应。
我看 dist wxss 里面有 em,px,rpx，请问是有什么特殊的考虑吗？

**Comment by BearJ** [comment]
你好，是这样的：
- rpx是比较适合活动宣传页那种偏展示型的h5，因为是可以根据宽度等比缩放。而weui主要是服务于基础组件，所以基本单位还是使用px。
- 使用em是因为部分组件（例如cell）是需要考虑到字号放大的问题。
- 至于weui里面使用到rpx的，是为了方便地实现高清1像素线的。
