### ISSUE TITLE
找不到reset.wxss

### ISSUE THREAD

**Issue by cocoli** [weui/weui-wxss#12]
![888](https://cloud.githubusercontent.com/assets/3488475/20780776/b0f6d73c-b7b8-11e6-8cce-979b3dedc0a1.png)
![777](https://cloud.githubusercontent.com/assets/3488475/20780779/b74d29a6-b7b8-11e6-9032-3f7d52cbdfce.png)

**Comment by cocoli** [comment]
引入weui.wxss,还需要添加reset.wxss吗

**Comment by progrape** [comment]
引入 `dist/style/weui.wxss` 这个文件，而不是 src 目录下的
