### ISSUE TITLE
list navigator下折行

### ISSUE THREAD

**Issue by tobeacoder** [weui/weui-wxss#14]

**Comment by tobeacoder** [comment]
list     navigator下折行，ios系统，项目真机预览时发生，本地开发工具并不会出现这个问题。【微信版本问题】

**Comment by BearJ** [comment]
@tobeacoder 你好，可以发一下截图吗？

**Comment by tobeacoder** [comment]
@BearJ 微信app升级后未出现，应该是版本问题。
