### ISSUE TITLE
问个和 weui-wxss 无关的问题

### ISSUE THREAD

**Issue by zhaotoday** [weui/weui-wxss#17]
我想问个问题，微信小程序的**官方英文名称**是什么？  
目前看到的有 weapp（目测应该是 wechat app 的简称）、wxapp（微信 app 的简称）、mina。  
具体是哪个，或是其他的名称？

**Comment by BearJ** [comment]
@zhaotoday 这个还没有定论

**Comment by Emeryao** [comment]
`weapp`
微信开发者工具的代码里都是这么叫的
![image](https://cloud.githubusercontent.com/assets/3591899/21714801/e187c010-d43b-11e6-999c-b44f6bdd9c09.png)

**Comment by n7best** [comment]
英文版本微信上它叫mini program. 苹果应该不会允许叫app或者应用之类的东西

**Comment by zhaotoday** [comment]
@n7best 恩，应用（app）之类的词被苹果和谐了，我也看到了，官方叫：mini program。
