### ISSUE TITLE
navbar的activeIndex BUG

### ISSUE THREAD

**Issue by hejinguo** [weui/weui-wxss#20]
navbar组件，当activeIndex为0没问题，若调整activeIndex的默认值为1(既默认选中第二个tab时)，slider仍然标记在第一个位置上。

![qq 20161227164848](https://cloud.githubusercontent.com/assets/19966301/21495765/8a5c07ae-cc54-11e6-9778-438447a915da.png)

**Comment by BearJ** [comment]
@hejinguo 你好，这确实是bug，谢谢提醒

**Comment by BearJ** [comment]
新版已fixed
