### ISSUE TITLE
能否提供预览/体验WeUI的小程序？

### ISSUE THREAD

**Issue by Emeryao** [weui/weui-wxss#22]
像体验小程序[这个](https://mp.weixin.qq.com/debug/wxadoc/dev/demo.html?t=201715)一样

**Comment by progrape** [comment]
@Emeryao 你好，那个是小程序官方的demo，只要微信号绑定为小程序的开发中就能够预览，正常情况下只能预览自己的小程序。WeUI 的这个 demo，不能上架，也没有这个特权，所以暂时无法提供一个二维码预览，你可以自己下载代码，用开发者工具预览～

**Comment by Emeryao** [comment]
好吧 谢谢
