### ISSUE TITLE
weui document

### ISSUE THREAD

**Issue by bluedazzle** [weui/weui-wxss#3]
除了 example，weui for weapp 有文档嘛？现在没有的话有考虑加上文档嘛？

**Comment by chemzqm** [comment]
它们变化好快，我估计来不及写吧。

**Comment by bluedazzle** [comment]
哈哈哈

**Comment by czclk** [comment]
直接看example是可以的！

**Comment by BearJ** [comment]
@bluedazzle你好， 如果是指思想上的话，其实是和weui一致的。如果是用法上的话，像CodingLight所说，直接看example就好了，所有的所有都在example里。
