### ISSUE TITLE
开发者工具预览时，提示CssSyntaxError

### ISSUE THREAD

**Issue by lizhiyao** [weui/weui-wxss#32]
weui-wxss version: 1.1.1

项目引入 `dist/style/weui.wxss` 文件，

在开发者工具 调试 界面，可以正常运行；

在开发者工具 项目 界面，点击预览按钮，会提示 CssSyntaxError。

![wx20170325-134119](https://cloud.githubusercontent.com/assets/8143023/24319794/6fbd3772-1161-11e7-9321-f7087cf657de.png)

**Comment by lizhiyao** [comment]
问题已解决。

问题的原因为：我把 `weui-wxss` 这个项目 clone 到本地小程序项目目录的 vendor 文件夹，并引用了 `weui-wxss/dist/style/weui.wxss` 文件。这样做在使用微信开发者工具调试时是 ok 的，但是当上传/预览时，就会报上述截图的错误。

解决方案：仅把 `weui-wxss/dist/style/weui.wxss` 文件放入 `vendor` 文件夹并进行引用。

**Comment by BearJ** [comment]
正解~只引入weui.wxss即可~
