### ISSUE TITLE
PC 调试没问题，生成项目预览报错

### ISSUE THREAD

**Issue by nepaul** [weui/weui-wxss#39]
使用方式：通过在 app.wxss 导入 `@import './components/weui-wxss/dist/style/weui.wxss';`

如下：
<img width="603" alt="default" src="https://cloud.githubusercontent.com/assets/1112181/25312872/395e9d5e-2856-11e7-9fe9-735934f88469.png">

**Comment by progrape** [comment]
@nepaul 你在项目中放编译好的 `weui.wxss` 就好了，不要把源码放进去。预览的时候工具会把全部文件都编译一把，开发者工具编译不了那些 LESS 源码，从报错信息也看得出来。

**Comment by nepaul** [comment]
果然，谢谢！
