### ISSUE TITLE
微信 web 开发者工具下的样式问题

### ISSUE THREAD

**Issue by zhaotoday** [weui/weui-wxss#5]
SearchBar 组件在微信 web 开发者工具下，输入框未聚焦时的图标样式有问题。

**Comment by progrape** [comment]
@zhaotoday 可否提供一下截图？看起来更直观

**Comment by zhaotoday** [comment]
@progrape 
![2222](https://cloud.githubusercontent.com/assets/8154625/20342345/fb62d130-ac24-11e6-90fd-fe0a8cb60779.jpg)

**Comment by progrape** [comment]
@zhaotoday 收到~

**Comment by BearJ** [comment]
@zhaotoday 这个bug在真机上是没有的，等待开发者工具的fix吧

**Comment by zhaotoday** [comment]
@BearJ 好的。
