### ISSUE TITLE
在真机下搜索也会出现问题

### ISSUE THREAD

**Issue by zouzhenxing** [weui/weui-wxss#7]
![image](https://cloud.githubusercontent.com/assets/16457664/20469792/8981d090-afdd-11e6-8149-a8a971f826ea.png)
我的解决办法如下：
![image](https://cloud.githubusercontent.com/assets/16457664/20469958/3da39c1a-afdf-11e6-9ad8-cb8b9dfbb21c.png)
真机图片如下：
![image](https://cloud.githubusercontent.com/assets/16457664/20469971/5415b85c-afdf-11e6-9421-35f819a40f60.png)

**Comment by BearJ** [comment]
好的，谢谢，这的确是个BUG

**Comment by fuchao2012** [comment]
在搜索的样式里添加 
search.wxss

```
.weui-icon-search{
    font-size: inherit;
}
```

可解决。

**Comment by BearJ** [comment]
这里fixed了~
