### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by zouzhenxing** [weui/weui-wxss#8]
![image](https://cloud.githubusercontent.com/assets/16457664/20472731/db6cb30c-aff6-11e6-8ff9-de592ced9038.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472737/e72085ca-aff6-11e6-8166-089dda7860f1.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472757/0767efd0-aff7-11e6-9214-004b1964b667.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472762/0ba2b418-aff7-11e6-86cb-dae3e5fcd348.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472766/12b305aa-aff7-11e6-8dc2-488d8aff35e5.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472777/20ac7fe2-aff7-11e6-955a-190d1e042756.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472780/28e67424-aff7-11e6-8006-3e05ff43e853.png)
![image](https://cloud.githubusercontent.com/assets/16457664/20472793/3694186a-aff7-11e6-9dd5-bf18f23ba0e8.png)

**Comment by BearJ** [comment]
你好，请问这个issue是有啥问题不？

**Comment by BearJ** [comment]
@zouzhenxing 这是编译之后的代码，所以是会存在样式复写的现象。如果想看源码，可以看src/下的。
